# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reserveMyStuff' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'IoniconsSwift', :git => 'http://github.com/tidwall/IoniconsSwift.git', :branch => 'master' # Icon source lib
  pod 'Kingfisher', '~> 5.4.0' # Async image fetching & cache
  pod 'R.swift', '~> 5.1.0' # Get strong typed, autocompleted resources like images, fonts and segues in Swift projects

  target 'reserveMyStuffTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
